version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: post-service-container
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data


  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    
    environment:
      RABBITMQ_DEFAULT_USER: user 
      RABBITMQ_DEFAULT_PASS: password

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  redis-data:
  rabbitmq-data: