version: '3.8'

services:
  redis:
    image: redis:7.2.4-alpine  # Specific stable version
    container_name: social-media-microservices
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.12-management  # Version with management UI
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user 
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  redis-data:
  rabbitmq-data:
